# Generated by Django 5.2.12 on 2026-08-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='organisation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
