# Generated by Django 5.2.12 on 2026-08-13 06:42

import django.db.models.deletion
import modelcluster.fields
import public_content.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(help_text="A short introduction to LaBio Media's pricing approach.", max_length=1500)),
                ('positioning_message', models.TextField(help_text='Explain that projects are scoped individually and note any custom-pricing eligibility.', max_length=1500)),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(public_content.models.HeadlessPageMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('price_label', models.CharField(help_text='Editorial text such as "From €400".', max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('features', wagtail.fields.StreamField([('feature', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Included feature', 'max_length': 255})})),
                ('cta_label', models.CharField(max_length=100)),
                ('cta_url', models.URLField(help_text='Use the full public destination URL.', max_length=500)),
                ('active', models.BooleanField(default=True, help_text='Inactive items stay in the CMS but are hidden publicly.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_items', to='public_content.pricingpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
