# Generated by Django 5.2.12 on 2026-08-20 12:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def link_existing_collaborators(apps, schema_editor):
    HomePage = apps.get_model("public_content", "HomePage")
    Collaborator = apps.get_model("public_content", "Collaborator")
    HomePageCollaborator = apps.get_model(
        "public_content",
        "HomePageCollaborator",
    )

    collaborators = list(
        Collaborator.objects.filter(active=True, live=True).order_by(
            "display_order",
            "organization_name",
            "pk",
        )
    )
    HomePageCollaborator.objects.bulk_create(
        [
            HomePageCollaborator(
                page=home,
                collaborator=collaborator,
                sort_order=sort_order,
            )
            for home in HomePage.objects.all()
            for sort_order, collaborator in enumerate(collaborators)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0002_pricingpage_pricingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='collaborators_enabled',
            field=models.BooleanField(default=True, help_text='Show the collaborators section on the public homepage.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collaborators_heading',
            field=models.CharField(default='Trusted by research groups and organisations', max_length=255),
        ),
        migrations.CreateModel(
            name='HomePageCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='public_content.collaborator')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_collaborators', to='public_content.homepage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'collaborator'), name='unique_homepage_collaborator')],
            },
        ),
        migrations.RunPython(
            link_existing_collaborators,
            migrations.RunPython.noop,
        ),
    ]
