# Generated by Django 5.2.12 on 2026-08-22 08:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def link_existing_testimonials(apps, schema_editor):
    HomePage = apps.get_model("public_content", "HomePage")
    Testimonial = apps.get_model("public_content", "Testimonial")
    HomePageTestimonial = apps.get_model(
        "public_content",
        "HomePageTestimonial",
    )
    database = schema_editor.connection.alias

    testimonials = list(
        Testimonial.objects.using(database)
        .filter(active=True, live=True)
        .order_by("pk")
    )
    HomePageTestimonial.objects.using(database).bulk_create(
        [
            HomePageTestimonial(
                page=home,
                testimonial=testimonial,
                sort_order=sort_order,
            )
            for home in HomePage.objects.using(database).all()
            for sort_order, testimonial in enumerate(testimonials)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0003_homepage_collaborators_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_cta_label',
            field=models.CharField(blank=True, default='More about LaBio Media', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_cta_url',
            field=models.URLField(blank=True, default='https://labiomedia.com/about', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_enabled',
            field=models.BooleanField(default=True, help_text='Show the about section on the public homepage.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_eyebrow',
            field=models.CharField(blank=True, default='About LaBio Media', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_enabled',
            field=models.BooleanField(default=True, help_text='Show the contact section on the public homepage.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_eyebrow',
            field=models.CharField(blank=True, default='Contact', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work_cta_label',
            field=models.CharField(blank=True, default='View all work', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work_cta_url',
            field=models.URLField(blank=True, default='https://labiomedia.com/work', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work_enabled',
            field=models.BooleanField(default=True, help_text='Show the selected work section on the public homepage.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work_eyebrow',
            field=models.CharField(blank=True, default='Selected work', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work_heading',
            field=models.CharField(default='Turning research into meaningful stories', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_cta_label',
            field=models.CharField(blank=True, default='See all services', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_cta_url',
            field=models.URLField(blank=True, default='https://labiomedia.com/services', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_enabled',
            field=models.BooleanField(default=True, help_text='Show the services section on the public homepage.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_eyebrow',
            field=models.CharField(blank=True, default='What we do', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_heading',
            field=models.CharField(default='Communication solutions for research and innovation.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_enabled',
            field=models.BooleanField(default=True, help_text='Show selected testimonials on the public homepage.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_heading',
            field=models.CharField(default='Client perspectives', max_length=255),
        ),
        migrations.CreateModel(
            name='HomePageTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_testimonials', to='public_content.homepage')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='public_content.testimonial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'testimonial'), name='unique_homepage_testimonial')],
            },
        ),
        migrations.RunPython(
            link_existing_testimonials,
            migrations.RunPython.noop,
        ),
    ]
