# Generated by Django 5.2.12 on 2026-08-22 09:55

import django.db.models.deletion
import public_content.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0004_homepage_about_cta_label_homepage_about_cta_url_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('article_type', models.CharField(choices=[('insight', 'Insight'), ('milestone', 'Milestone'), ('update', 'Update')], default='update', max_length=20)),
                ('summary', models.TextField(max_length=1000)),
                ('featured_image_alt', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('quote', 10), ('embed', 11), ('cta', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('public_content.blocks.PublicRichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 1000}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('quote', 8), ('attribution', 9)]], {}), 11: ('public_content.blocks.PublicEmbedBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 13: ('wagtail.blocks.URLBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('label', 12), ('url', 13)]], {})})),
                ('featured_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(public_content.models.HeadlessPageMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(max_length=1000)),
                ('featured_image_alt', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('registration_url', models.URLField(blank=True, max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('quote', 10), ('embed', 11), ('cta', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('public_content.blocks.PublicRichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 1000}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('quote', 8), ('attribution', 9)]], {}), 11: ('public_content.blocks.PublicEmbedBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 13: ('wagtail.blocks.URLBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('label', 12), ('url', 13)]], {})})),
                ('featured_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(public_content.models.HeadlessPageMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='UpdatesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(public_content.models.HeadlessPageMixin, 'wagtailcore.page', models.Model),
        ),
    ]
