# Generated by Django 5.2.12 on 2026-08-22 10:28

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def backfill_editorial_home_about(apps, schema_editor):
    database = schema_editor.connection.alias
    HomePage = apps.get_model("public_content", "HomePage")
    AboutPage = apps.get_model("public_content", "AboutPage")
    Testimonial = apps.get_model("public_content", "Testimonial")
    HomePageTestimonial = apps.get_model(
        "public_content",
        "HomePageTestimonial",
    )
    AboutPageTestimonial = apps.get_model(
        "public_content",
        "AboutPageTestimonial",
    )

    HomePage.objects.using(database).update(
        updates_enabled=True,
        updates_eyebrow="From LaBio",
        updates_heading="A few notes, ideas and milestones.",
        updates_item_count=3,
        updates_cta_label="View all updates",
        updates_cta_url="https://labiomedia.com/updates",
    )
    AboutPage.objects.using(database).update(
        page_eyebrow="About LaBio Media",
        values_label="Values",
        process_label="How we work",
        testimonials_enabled=True,
        testimonials_heading="Client perspectives",
    )

    active_testimonial_ids = set(
        Testimonial.objects.using(database)
        .filter(live=True, active=True)
        .values_list("pk", flat=True)
    )
    testimonial_ids = [
        testimonial_id
        for testimonial_id in (
            HomePageTestimonial.objects.using(database)
            .order_by("page_id", "sort_order", "pk")
            .values_list("testimonial_id", flat=True)
        )
        if testimonial_id in active_testimonial_ids
    ]
    if not testimonial_ids:
        testimonial_ids = sorted(active_testimonial_ids)
    for page_id in AboutPage.objects.using(database).values_list(
        "pk",
        flat=True,
    ):
        for sort_order, testimonial_id in enumerate(testimonial_ids):
            AboutPageTestimonial.objects.using(database).get_or_create(
                page_id=page_id,
                testimonial_id=testimonial_id,
                defaults={"sort_order": sort_order},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0005_articlepage_eventpage_updatesindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='page_eyebrow',
            field=models.CharField(blank=True, default='About LaBio Media', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_label',
            field=models.CharField(blank=True, default='How we work', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='testimonials_enabled',
            field=models.BooleanField(default=True, help_text='Show selected testimonials on the public About page.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='testimonials_heading',
            field=models.CharField(default='Client perspectives', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_label',
            field=models.CharField(blank=True, default='Values', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updates_cta_label',
            field=models.CharField(blank=True, default='View all updates', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updates_cta_url',
            field=models.URLField(blank=True, default='https://labiomedia.com/updates', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updates_enabled',
            field=models.BooleanField(default=True, help_text='Show the latest published updates on the public homepage.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updates_eyebrow',
            field=models.CharField(blank=True, default='From LaBio', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updates_heading',
            field=models.CharField(default='A few notes, ideas and milestones.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updates_item_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of latest published updates to show (1–6).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.CreateModel(
            name='AboutPageTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_testimonials', to='public_content.aboutpage')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='public_content.testimonial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'testimonial'), name='unique_aboutpage_testimonial')],
            },
        ),
        migrations.RunPython(
            backfill_editorial_home_about,
            migrations.RunPython.noop,
        ),
    ]
