# Generated by Django 5.2.12 on 2026-08-22 11:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0006_aboutpage_page_eyebrow_aboutpage_process_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudypage',
            name='approach',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='challenge',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='cta_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='deliverables',
            field=wagtail.fields.StreamField([('deliverable', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Deliverable', 'max_length': 255})}),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='outcome',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='project_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='project_year',
            field=models.CharField(blank=True, help_text='Editorial year or range, such as "2025" or "2024–2025".', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='client_display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
