# Generated by Django 5.2.12 on 2026-08-22 12:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0007_casestudypage_approach_casestudypage_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingitem',
            name='context',
            field=models.TextField(blank=True, help_text='Optional scope, exclusions, or other pricing context.', max_length=2000),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='currency',
            field=models.CharField(blank=True, default='€', help_text='Currency symbol or code, such as "€" or "EUR".', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='featured',
            field=models.BooleanField(default=False, help_text='Give this offer subtle emphasis on the public pricing page.'),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='ideal_for',
            field=models.TextField(blank=True, help_text='Who this offer is designed for.', max_length=1500),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='pricing_mode',
            field=models.CharField(choices=[('starting_from', 'Starting from'), ('fixed', 'Fixed price'), ('custom', 'Custom / contact us')], default='starting_from', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='related_case_studies',
            field=wagtail.fields.StreamField([('case_study', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Case study', 'page_type': ['public_content.CaseStudyPage']})}),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='related_services',
            field=wagtail.fields.StreamField([('service', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Service', 'page_type': ['public_content.ServicePage']})}),
        ),
        migrations.AlterField(
            model_name='pricingitem',
            name='price_label',
            field=models.CharField(help_text='Enter the amount, such as "1,500", or custom wording such as "Let’s talk". Existing formatted labels remain supported.', max_length=100),
        ),
    ]
