# Generated by Django 5.2.12 on 2026-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0008_pricingitem_context_pricingitem_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
