# Generated by Django 5.2.12 on 2026-08-22 14:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0010_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navigation_links',
            field=wagtail.fields.StreamField([('navigation_link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('enabled', 3), ('external', 4)]], {})}),
        ),
    ]
