# Generated by Django 5.2.12 on 2026-08-23 17:21

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def backfill_service_editorial_selections(apps, schema_editor):
    ServicePage = apps.get_model("public_content", "ServicePage")
    CaseStudyPage = apps.get_model("public_content", "CaseStudyPage")
    Testimonial = apps.get_model("public_content", "Testimonial")
    RelatedCaseStudy = apps.get_model(
        "public_content",
        "ServicePageRelatedCaseStudy",
    )
    ServiceTestimonial = apps.get_model(
        "public_content",
        "ServicePageTestimonial",
    )
    case_study_services = CaseStudyPage.services.through
    database = schema_editor.connection.alias

    for service in ServicePage.objects.using(database).iterator():
        case_study_ids = (
            case_study_services.objects.using(database)
            .filter(servicepage_id=service.pk)
            .order_by("casestudypage_id")
            .values_list("casestudypage_id", flat=True)
        )
        RelatedCaseStudy.objects.using(database).bulk_create(
            [
                RelatedCaseStudy(
                    page_id=service.pk,
                    case_study_id=case_study_id,
                    sort_order=sort_order,
                )
                for sort_order, case_study_id in enumerate(case_study_ids)
            ]
        )

        testimonial_ids = (
            Testimonial.objects.using(database)
            .filter(related_service_id=service.pk)
            .order_by("pk")
            .values_list("pk", flat=True)
        )
        ServiceTestimonial.objects.using(database).bulk_create(
            [
                ServiceTestimonial(
                    page_id=service.pk,
                    testimonial_id=testimonial_id,
                    sort_order=sort_order,
                )
                for sort_order, testimonial_id in enumerate(testimonial_ids)
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0011_sitesettings_navigation_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='cta_heading',
            field=models.CharField(default='Have a project in mind?', max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='related_work_enabled',
            field=models.BooleanField(default=True, help_text='Show selected case studies on the public service page.'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='related_work_heading',
            field=models.CharField(default='Related work', max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='testimonials_enabled',
            field=models.BooleanField(default=True, help_text='Show selected testimonials on the public service page.'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='testimonials_heading',
            field=models.CharField(default='Client perspectives', max_length=255),
        ),
        migrations.CreateModel(
            name='ServicePageRelatedCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='public_content.casestudypage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_related_case_studies', to='public_content.servicepage')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('page', 'case_study'), name='unique_servicepage_related_case_study')],
            },
        ),
        migrations.CreateModel(
            name='ServicePageTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_testimonials', to='public_content.servicepage')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='public_content.testimonial')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('page', 'testimonial'), name='unique_servicepage_testimonial')],
            },
        ),
        migrations.RunPython(
            backfill_service_editorial_selections,
            migrations.RunPython.noop,
        ),
    ]
