# Generated by Django 5.2.12 on 2026-08-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0012_servicepage_cta_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='hero_image_alt',
        ),
    ]
