# Generated by Django 5.2.12 on 2026-08-24 10:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0013_remove_servicepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudypage',
            name='showcase',
            field=wagtail.fields.StreamField([('photo_slider', 6), ('masonry_gallery', 8), ('image_grid', 11), ('image_pair', 14), ('video', 16), ('website_preview_grid', 21), ('wide_image', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Slides', 'max_num': 20, 'min_num': 2}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 30, 'min_num': 2}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two columns'), ('3', 'Three columns')]}), 10: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 24, 'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('columns', 9), ('images', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'First image'}), 13: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'Second image'}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('first_image', 12), ('second_image', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'YouTube or Vimeo URL'}), 16: ('wagtail.blocks.StructBlock', [[('heading', 0), ('url', 15), ('caption', 3)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 150}), 18: ('wagtail.blocks.URLBlock', (), {'label': 'Optional destination URL', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('label', 17), ('url', 18), ('caption', 3)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'label': 'Website previews', 'max_num': 12, 'min_num': 1}), 21: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 20)]], {}), 22: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 1), ('alt_text', 2), ('caption', 3)]], {})}, help_text='Optional ordered visual modules. When empty, the legacy embed and gallery remain the public visual presentation.'),
        ),
    ]
