# Generated by Django 5.2.12 on 2026-08-24 18:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0014_casestudypage_showcase'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='showcase',
            field=wagtail.fields.StreamField([('masonry_gallery', 6), ('image_grid', 9), ('image_pair', 12), ('video', 14), ('wide_image', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 30, 'min_num': 2}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 5)]], {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two columns'), ('3', 'Three columns')]}), 8: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 24, 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('columns', 7), ('images', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'First image'}), 11: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'Second image'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('first_image', 10), ('second_image', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'YouTube or Vimeo URL'}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('url', 13), ('caption', 3)]], {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 1), ('alt_text', 2), ('caption', 3)]], {})}, help_text='Optional ordered images and videos for the article body.'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='showcase',
            field=wagtail.fields.StreamField([('masonry_gallery', 6), ('image_grid', 9), ('image_pair', 12), ('video', 14), ('wide_image', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 30, 'min_num': 2}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 5)]], {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two columns'), ('3', 'Three columns')]}), 8: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 24, 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('columns', 7), ('images', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'First image'}), 11: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'Second image'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('first_image', 10), ('second_image', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'YouTube or Vimeo URL'}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('url', 13), ('caption', 3)]], {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 1), ('alt_text', 2), ('caption', 3)]], {})}, help_text='Optional ordered images and videos for the event body.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
