# Generated by Django 5.2.17 on 2026-09-14 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0016_testimonial_portrait'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='team_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_heading',
            field=models.CharField(default='Our team', max_length=255),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('professional_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
