# Generated by Django 5.2.17 on 2026-09-23 13:45

import json
from html import escape
from uuid import NAMESPACE_URL, uuid5

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def legacy_narrative(content):
    """Copy plain text verbatim as escaped editorial HTML, without rewriting it."""
    def paragraph(text):
        return "".join(
            "<p>" + escape(part).replace("\n", "<br>") + "</p>"
            for part in text.replace("\r\n", "\n").split("\n\n")
        )

    parts = []
    for field, heading in (("challenge", "Challenge"), ("approach", "Approach")):
        if content.get(field):
            parts.append(f"<h3>{heading}</h3>" + paragraph(content[field]))
    deliverables = content.get("deliverables") or []
    if isinstance(deliverables, str):
        deliverables = json.loads(deliverables)
    items = [item["value"] for item in deliverables if item["type"] == "deliverable"]
    if items:
        parts.append("<h3>Deliverables</h3><ul>" + "".join(
            "<li>" + escape(item) + "</li>" for item in items
        ) + "</ul>")
    if content.get("outcome"):
        parts.append("<h3>Outcome</h3>" + paragraph(content["outcome"]))
    html = "".join(parts)
    return [{"type": "rich_text", "value": html, "id": str(uuid5(NAMESPACE_URL, html))}] if html else []


def migrate_narratives(apps, schema_editor):
    alias = schema_editor.connection.alias
    CaseStudy = apps.get_model("public_content", "CaseStudyPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    ContentType = apps.get_model("contenttypes", "ContentType")
    for page in CaseStudy.objects.using(alias).all().iterator():
        if not page.narrative:
            content = {name: getattr(page, name) for name in ("challenge", "approach", "outcome")}
            content["deliverables"] = page.deliverables.get_prep_value()
            CaseStudy.objects.using(alias).filter(pk=page.pk).update(narrative=legacy_narrative(content))
    content_type = ContentType.objects.using(alias).filter(
        app_label="public_content", model="casestudypage"
    ).first()
    if content_type is None:
        return
    # Convert each snapshot independently: never copy a draft onto the live page.
    for revision in Revision.objects.using(alias).filter(content_type_id=content_type.pk).iterator():
        content = revision.content
        if "narrative" not in content:
            content["narrative"] = json.dumps(legacy_narrative(content))
            Revision.objects.using(alias).filter(pk=revision.pk).update(content=content)


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0018_home_selected_work_summary'),
        ('wagtailimages', '0027_image_description'),
    ]

    # Legacy columns and original revision keys remain available for recovery.
    # Reversing removes only the new narrative; it cannot erase the original text.
    operations = [
        migrations.AddField(
            model_name='casestudypage',
            name='narrative',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('public_content.blocks.NarrativeRichTextBlock', (), {})}, help_text='Project story: use headings, paragraphs and nested lists. Add visuals in Showcase.'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='showcase',
            field=wagtail.fields.StreamField([('photo_slider', 6), ('masonry_gallery', 8), ('image_grid', 11), ('image_pair', 14), ('video', 16), ('website_preview_grid', 21), ('wide_image', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Slides', 'max_num': 20, 'min_num': 2}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 30, 'min_num': 2}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two columns'), ('3', 'Three columns')]}), 10: ('wagtail.blocks.ListBlock', (4,), {'label': 'Images', 'max_num': 24, 'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('columns', 9), ('images', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'First image'}), 13: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3)]], {'label': 'Second image'}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('first_image', 12), ('second_image', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'YouTube or Vimeo URL'}), 16: ('wagtail.blocks.StructBlock', [[('heading', 0), ('url', 15), ('caption', 3)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 150}), 18: ('wagtail.blocks.URLBlock', (), {'label': 'Optional destination URL', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('label', 17), ('url', 18), ('caption', 3)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'label': 'Website previews', 'max_num': 12, 'min_num': 1}), 21: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 20)]], {}), 22: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 1), ('alt_text', 2), ('caption', 3)]], {})}, help_text='Optional ordered visual modules, displayed after the narrative.'),
        ),
        migrations.RunPython(migrate_narratives, migrations.RunPython.noop),
    ]
