# Generated by Django 5.2.17 on 2026-09-30 18:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0022_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='showcase',
            field=wagtail.fields.StreamField([('print_design', 1), ('photo_slider', 8), ('masonry_gallery', 10), ('image_grid', 13), ('image_pair', 16), ('video', 18), ('website_preview_grid', 23), ('wide_image', 24)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('public_content.Publication',), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('publication', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('alt_text', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Slides', 'max_num': 20, 'min_num': 2}), 8: ('wagtail.blocks.StructBlock', [[('heading', 2), ('images', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (6,), {'label': 'Images', 'max_num': 30, 'min_num': 2}), 10: ('wagtail.blocks.StructBlock', [[('heading', 2), ('images', 9)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two columns'), ('3', 'Three columns')]}), 12: ('wagtail.blocks.ListBlock', (6,), {'label': 'Images', 'max_num': 24, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('heading', 2), ('columns', 11), ('images', 12)]], {}), 14: ('wagtail.blocks.StructBlock', [[('image', 3), ('alt_text', 4), ('caption', 5)]], {'label': 'First image'}), 15: ('wagtail.blocks.StructBlock', [[('image', 3), ('alt_text', 4), ('caption', 5)]], {'label': 'Second image'}), 16: ('wagtail.blocks.StructBlock', [[('heading', 2), ('first_image', 14), ('second_image', 15)]], {}), 17: ('wagtail.blocks.URLBlock', (), {'label': 'YouTube or Vimeo URL'}), 18: ('wagtail.blocks.StructBlock', [[('heading', 2), ('url', 17), ('caption', 5)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 150}), 20: ('wagtail.blocks.URLBlock', (), {'label': 'Optional destination URL', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('image', 3), ('alt_text', 4), ('label', 19), ('url', 20), ('caption', 5)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'label': 'Website previews', 'max_num': 12, 'min_num': 1}), 23: ('wagtail.blocks.StructBlock', [[('heading', 2), ('items', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('heading', 2), ('image', 3), ('alt_text', 4), ('caption', 5)]], {})}, help_text='Optional ordered visual modules, displayed after the narrative.'),
        ),
    ]
