# Generated by Django 5.2.17 on 2026-10-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0023_case_study_print_design'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudypage',
            name='portfolio_thumbnail',
            field=models.ForeignKey(blank=True, help_text='Optional project-card image used on Home, Work and Related Work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='dark_logo',
            field=models.ForeignKey(blank=True, help_text='Optional dark-theme asset. The default logo is used when empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
