# Generated by Django 5.2.11 on 2026-08-12 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_updated_at_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('planning', 'Planning'), ('pre-production', 'Pre-production'), ('production', 'Production'), ('review', 'Review'), ('approval', 'Approval'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('raw', 'Raw'), ('preview', 'Preview'), ('approval', 'Approval'), ('final_delivery', 'Final delivery')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes requested')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='clients.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='clients.project')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='clients.projectfile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('file', 'client'), name='unique_file_approval_per_client')],
            },
        ),
    ]
