# Generated by Django 5.2.11 on 2026-08-12 08:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_project_budget_project_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=cloudinary.models.CloudinaryField(
                folder='projects',
                max_length=255,
                resource_type='raw',
                type='private',
                verbose_name='file',
            ),
        ),
    ]
