# Generated by Django 5.2.12 on 2026-08-12 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_project_file_metadata(apps, schema_editor):
    ProjectFile = apps.get_model('clients', 'ProjectFile')

    for project_file in ProjectFile.objects.all().iterator():
        resource = project_file.file
        resource_type = getattr(resource, 'resource_type', None) or 'raw'
        delivery_type = getattr(resource, 'type', None) or 'private'
        public_id = getattr(resource, 'public_id', None) or str(resource)
        provider_format = (getattr(resource, 'format', None) or '').lower()
        version = getattr(resource, 'version', None)
        try:
            version = int(version) if version is not None else None
        except (TypeError, ValueError):
            version = None

        filename = project_file.filename or ''
        extension = filename.rsplit('.', 1)[-1].lower() if '.' in filename else ''
        if resource_type == 'raw':
            raw_extension = provider_format or extension
            suffix = f'.{raw_extension}' if raw_extension else ''
            if suffix and not public_id.lower().endswith(suffix.lower()):
                public_id = f'{public_id}{suffix}'

        ProjectFile.objects.filter(pk=project_file.pk).update(
            extension=extension,
            storage_provider='cloudinary',
            provider_public_id=public_id,
            provider_resource_type=resource_type,
            provider_delivery_type=delivery_type,
            provider_format=provider_format,
            provider_version=version,
        )


def reverse_legacy_project_file_metadata(apps, schema_editor):
    ProjectFile = apps.get_model('clients', 'ProjectFile')
    ProjectFile.objects.update(
        extension='',
        provider_public_id='',
        provider_resource_type='',
        provider_delivery_type='',
        provider_format='',
        provider_version=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_portal_staff_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='extension',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='provider_asset_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='provider_delivery_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('authenticated', 'Authenticated'), ('upload', 'Legacy public upload')], max_length=20),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='provider_format',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='provider_public_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='provider_resource_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('raw', 'Raw')], max_length=16),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='provider_version',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='storage_provider',
            field=models.CharField(choices=[('cloudinary', 'Cloudinary')], default='cloudinary', max_length=32),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='revisions', to='clients.projectfile'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('superseded', 'Superseded')], default='pending', max_length=20),
        ),
        migrations.RunPython(
            backfill_legacy_project_file_metadata,
            reverse_legacy_project_file_metadata,
        ),
        migrations.AddConstraint(
            model_name='projectfile',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_asset_id', ''), _negated=True), fields=('storage_provider', 'provider_asset_id'), name='unique_project_file_provider_asset'),
        ),
    ]
