"""
Django settings for labio project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import cloudinary
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(f"{name} must be a boolean value.")


def env_list(name, default=()):
    value = os.environ.get(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


def required_setting(name, development_default=None):
    value = os.environ.get(name)
    if value:
        return value
    if IS_PRODUCTION or development_default is None:
        raise ImproperlyConfigured(f"{name} must be configured.")
    return development_default


IS_PRODUCTION = (
    os.environ.get("DJANGO_ENV", "").strip().lower() == "production"
    or env_bool("RENDER", False)
)


def url_setting(name, development_default):
    value = required_setting(name, development_default)
    if IS_PRODUCTION and not value.startswith("https://"):
        raise ImproperlyConfigured(f"{name} must use HTTPS in production.")
    return value


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # The production API is reached through Render's single trusted proxy.
    # Local development ignores forwarded headers by default.
    'NUM_PROXIES': int(os.environ.get(
        'DRF_NUM_PROXIES',
        '1' if IS_PRODUCTION else '0',
    )),
}

SECRET_KEY = required_setting("SECRET_KEY")
if IS_PRODUCTION and len(SECRET_KEY) < 50:
    raise ImproperlyConfigured("SECRET_KEY must be at least 50 characters in production.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DEBUG must be disabled in production.")

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    ["localhost", "127.0.0.1", "[::1]"],
)
if IS_PRODUCTION and not os.environ.get("ALLOWED_HOSTS"):
    raise ImproperlyConfigured("ALLOWED_HOSTS must be configured in production.")

render_external_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if (
    IS_PRODUCTION
    and render_external_hostname
    and render_external_hostname not in ALLOWED_HOSTS
):
    ALLOWED_HOSTS.append(render_external_hostname)

if IS_PRODUCTION and "*" in ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS cannot contain '*' in production.")

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", IS_PRODUCTION)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", IS_PRODUCTION)

# Render terminates TLS at its trusted proxy and forwards the original scheme.
TRUST_X_FORWARDED_PROTO = env_bool("TRUST_X_FORWARDED_PROTO", IS_PRODUCTION)
if TRUST_X_FORWARDED_PROTO:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if IS_PRODUCTION and SECURE_SSL_REDIRECT and not TRUST_X_FORWARDED_PROTO:
    raise ImproperlyConfigured(
        "TRUST_X_FORWARDED_PROTO must be enabled with SECURE_SSL_REDIRECT on Render."
    )

if IS_PRODUCTION and "SECURE_HSTS_SECONDS" not in os.environ:
    raise ImproperlyConfigured(
        "SECURE_HSTS_SECONDS must be chosen explicitly in production."
    )
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
if SECURE_HSTS_SECONDS < 0:
    raise ImproperlyConfigured("SECURE_HSTS_SECONDS cannot be negative.")
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'storages',
    'rest_framework',
    'wagtail.contrib.settings',
    'wagtail.api.v2',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',
    'public_content',
    'clients',
    'contacts',
    'corsheaders',
    'messaging'

]
if IS_PRODUCTION and not os.environ.get("DATABASE_URL"):
    raise ImproperlyConfigured("DATABASE_URL must be configured in production.")

DATABASES = {
    'default': dj_database_url.config(conn_max_age=600)
}

cloudinary_credentials = {
    "CLOUDINARY_CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
    "CLOUDINARY_API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
    "CLOUDINARY_API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
}
if IS_PRODUCTION and not all(cloudinary_credentials.values()):
    raise ImproperlyConfigured(
        "All Cloudinary credential settings must be configured in production."
    )

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': cloudinary_credentials['CLOUDINARY_CLOUD_NAME'],
    'API_KEY': cloudinary_credentials['CLOUDINARY_API_KEY'],
    'API_SECRET': cloudinary_credentials['CLOUDINARY_API_SECRET'],
}

# Temporary ceiling for the synchronous browser -> Django -> Cloudinary path.
# This is deliberately not a ProjectFile model limit; a future signed direct-upload
# flow can support much larger assets without changing the ProjectFile schema.
PROJECT_FILE_PROXY_UPLOAD_MAX_BYTES = int(
    os.environ.get('PROJECT_FILE_PROXY_UPLOAD_MAX_BYTES', '100000000')
)

CONTACT_SUBMISSION_RATE_LIMIT = int(
    os.environ.get('CONTACT_SUBMISSION_RATE_LIMIT', '5')
)
CONTACT_SUBMISSION_RATE_WINDOW_SECONDS = int(
    os.environ.get('CONTACT_SUBMISSION_RATE_WINDOW_SECONDS', '900')
)
if CONTACT_SUBMISSION_RATE_LIMIT < 1:
    raise ImproperlyConfigured("CONTACT_SUBMISSION_RATE_LIMIT must be positive.")
if CONTACT_SUBMISSION_RATE_WINDOW_SECONDS < 1:
    raise ImproperlyConfigured(
        "CONTACT_SUBMISSION_RATE_WINDOW_SECONDS must be positive."
    )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'labio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'labio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=4),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

INVITATION_FRONTEND_URL = url_setting(
    "INVITATION_FRONTEND_URL",
    "http://localhost:3000/accept-invitation",
)
PASSWORD_RESET_TIMEOUT = int(os.environ.get('INVITATION_TIMEOUT_SECONDS', 60 * 60 * 72))

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    ["http://localhost:3000"],
)
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    ["http://localhost:3000", "http://localhost:8000"],
)
if IS_PRODUCTION:
    for required_origin_setting in (
        "CORS_ALLOWED_ORIGINS",
        "CSRF_TRUSTED_ORIGINS",
    ):
        if not os.environ.get(required_origin_setting):
            raise ImproperlyConfigured(
                f"{required_origin_setting} must be configured in production."
            )
    insecure_origins = [
        origin
        for origin in CORS_ALLOWED_ORIGINS + CSRF_TRUSTED_ORIGINS
        if not origin.startswith("https://")
    ]
    if insecure_origins:
        raise ImproperlyConfigured(
            "CORS_ALLOWED_ORIGINS and CSRF_TRUSTED_ORIGINS must use HTTPS "
            "in production."
        )

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Helsinki'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

cms_media_access_key = os.environ.get('CMS_MEDIA_ACCESS_KEY_ID')
cms_media_secret_key = os.environ.get('CMS_MEDIA_SECRET_ACCESS_KEY')
cms_media_bucket = os.environ.get('CMS_MEDIA_BUCKET_NAME')
cms_media_custom_domain = os.environ.get('CMS_MEDIA_CUSTOM_DOMAIN')
cms_media_uses_s3 = bool(
    cms_media_access_key
    and cms_media_secret_key
    and cms_media_bucket
)
cms_media_is_partially_configured = any(
    [cms_media_access_key, cms_media_secret_key, cms_media_bucket]
) and not cms_media_uses_s3
if cms_media_is_partially_configured:
    raise ImproperlyConfigured(
        "CMS media access key, secret key, and bucket must be configured together."
    )
if IS_PRODUCTION and not cms_media_uses_s3:
    raise ImproperlyConfigured(
        "Persistent CMS media storage must be configured in production."
    )

if cms_media_uses_s3:
    cms_media_options = {
        'access_key': cms_media_access_key,
        'secret_key': cms_media_secret_key,
        'bucket_name': cms_media_bucket,
        'location': 'cms',
        'file_overwrite': False,
        'querystring_auth': False,
    }
    optional_cms_media_options = {
        'region_name': os.environ.get('CMS_MEDIA_REGION_NAME'),
        'endpoint_url': os.environ.get('CMS_MEDIA_ENDPOINT_URL'),
        # This R2 public binding serves the bucket below its bucket-name path.
        # Adding that path to django-storages' public domain changes generated
        # URLs only; object keys remain under the separate ``cms`` location.
        'custom_domain': (
            f"{cms_media_custom_domain.rstrip('/')}/{cms_media_bucket}"
            if cms_media_custom_domain
            else None
        ),
    }
    cms_media_options.update(
        {
            key: value
            for key, value in optional_cms_media_options.items()
            if value
        }
    )
    default_storage = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': cms_media_options,
    }
else:
    # Local development and tests must remain independent of production S3.
    default_storage = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': MEDIA_ROOT,
            'base_url': MEDIA_URL,
        },
    }

STORAGES = {
    'default': default_storage,
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000
WAGTAIL_SITE_NAME = 'LaBio Media CMS'
WAGTAILADMIN_BASE_URL = url_setting(
    "WAGTAILADMIN_BASE_URL",
    "http://localhost:8000",
)

RESEND_API_KEY = required_setting("RESEND_API_KEY", "")
EMAIL_FROM = required_setting("EMAIL_FROM", "dev-null@localhost")
CONTACT_EMAIL = required_setting("CONTACT_EMAIL", "dev-null@localhost")
DEFAULT_FROM_EMAIL = EMAIL_FROM
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
