# Generated by Django 5.2.11 on 2026-08-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_project_budget_project_project_type_and_more'),
        ('messaging', '0002_conversation_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='clients.project'),
        ),
    ]
